FROM php:7-fpm

# RUN apt-get update
# RUN docker-php-ext-install mysqli && docker-php-ext-enable mysqli

RUN mkdir -p /etc/php/
RUN mkdir -p /var/www/public_html/
RUN mkdir -p /var/www/application
RUN mkdir -p /var/www/system
